// ⚠️ This file is generated by tools/makeSources.mjs, ✋ do not modify

import './closeBlock.js';
import './finally.js';
import './gc.js';
import './if.js';
import './ifelse.js';
import './loop.js';
import './openBlock.js';
import './repeat.js';
import './stopped.js';
